config/routes.rb
Rails.application.routes.draw do
  get 'mail_managment/index'
  resources :templates
  devise_for :users
  root to: "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/mail_managment_controller.rb
class MailManagmentController < ApplicationController
  def index
    @templates = Template.all 
    @users = User.all
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: %i[ show edit update destroy ]

  # GET /templates or /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1 or /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates or /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to template_url(@template), notice: "Template was successfully created." }
        format.json { render :show, status: :created, location: @template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1 or /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to template_url(@template), notice: "Template was successfully updated." }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1 or /templates/1.json
  def destroy
    @template.destroy

    respond_to do |format|
      format.html { redirect_to templates_url, notice: "Template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def template_params
      params.require(:template).permit(:subject, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mail_managment_helper.rb
module MailManagmentHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/mail_managment/index.html.erb
<h1>Create a mailing list </h1>


<%= form_with url: 'http://localhost:3000/', method: :post do |f|%>
  <p>
    <%f.label :templates%> Select Template:
    <%= f.select :templates, @templates.collect{|i| [i.title,i.id]}%>  
    <br><br> 
  </p>
  <p>
    <%f.label :emails%> Selcet Users:
    <%= f.select :emails, @users.collect{|i| [i.email,i.id]},{ :multiple => true }%>  
    <br><br>
  </p>
  <p>
    <%f.label :dateinstructed%> Select date of delhivery
    <%= f.date_select :dateinstructed, :order => [:day, :month, :year] %>
    <br><br>
  </p>
  <%=f.submit%>
  <br> 

<% end %>

app/views/templates/_form.html.erb
<%= form_with(model: template) do |form| %>
  <% if template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
        <% template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/_template.html.erb
<div id="<%= dom_id template %>">
  <p>
    <strong>Subject:</strong>
    <%= template.subject %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= template.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= template.body %>
  </p>

</div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render "form", template: @template %>

<br>

<div>
  <%= link_to "Show this template", @template %> |
  <%= link_to "Back to templates", templates_path %>
</div>

app/views/templates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Templates</h1>

<div id="templates">
  <% @templates.each do |template| %>
    <%= render template %>
    <p>
      <%= link_to "Show this template", template %>
    </p>
  <% end %>
</div>

<%= link_to "New template", new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render "form", template: @template %>

<br>

<div>
  <%= link_to "Back to templates", templates_path %>
</div>

app/views/templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @template %>

<div>
  <%= link_to "Edit this template", edit_template_path(@template) %> |
  <%= link_to "Back to templates", templates_path %>

  <%= button_to "Destroy this template", @template, method: :delete %>
</div>